version: '3'

services:

  app:
    build: 
      context: ./backend
    container_name: app
    restart: always
    command: python server.py
    expose:
      - 5000
    networks:
      - backend

  nextjs:
    build:
      context: ./frontend
    container_name: nextjs
    restart: always
    command: npm run dev
    expose:
      - 3000
    networks:
      - backend

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - backend

networks:
  backend:
    driver: bridge

